"""Erzeugt notebooks/06b_delta.ipynb — flat vs. topografisch im Vergleich."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_notebook import md, code, nb, save

OUT = Path(
    "/sessions/intelligent-practical-clarke/mnt/Einsatz von Geodaten in Marketing"
    "/notebooks/06b_delta.ipynb"
)

cells = [
    md(
        "# 06b — Flat vs. topografisch: Delta-Analyse",
        "",
        "**Ziel:** Den Flat-Score (Notebook 05/06) mit dem topografischen Score (basierend auf Tobler-Walking-Zeiten) vergleichen — Zelle für Zelle. Das beantwortet die Frage: **wo verändert die Topografie das 15-Minuten-Stadt-Bild?**",
        "",
        "**Dateien:**",
        "- Input: `data/processed/zh_hex_grid.gpkg`, `data/processed/zh_pois.gpkg`, `data/processed/zh_walk_graph_topo.graphml`",
        "- Output: `data/processed/hex_score_topo.gpkg`, `reports/figures/score_flat_vs_topo.png`, `reports/figures/score_delta.html`",
        "",
        "**Annahmen:** Der flache Score nutzt Luftlinien-Distanzen + 5 km/h-Konstante. Der topografische Score nutzt Tobler-Walking-Zeiten auf dem realen Strassengraph mit Kanten-Steigung aus SwissALTI3D. Wir erwarten, dass besonders an Hangzonen (Zürichberg, Hönggerberg, Käferberg, Üetliberg) der topografische Score niedriger ausfällt als der flache.",
    ),
    md("## 1. Setup"),
    code(
        "import sys",
        "from pathlib import Path",
        "ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()",
        "sys.path.insert(0, str(ROOT / 'src'))",
        "",
        "import logging",
        "logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')",
        "",
        "import time",
        "import geopandas as gpd",
        "import numpy as np",
        "import osmnx as ox",
        "import pandas as pd",
        "import matplotlib.pyplot as plt",
        "",
        "from zh15min import config",
        "from zh15min.isochron import add_walk_time_tobler",
        "from zh15min.score import category_accessibility, total_score",
        "from zh15min.score_network import topographic_accessibility",
        "",
        "FIG = config.FIGURES_DIR",
        "FIG.mkdir(parents=True, exist_ok=True)",
    ),
    md("## 2. Inputs laden"),
    code(
        "grid = gpd.read_file(config.PROCESSED_DIR / 'zh_hex_grid.gpkg', layer='grid')",
        "pois = gpd.read_file(config.PROCESSED_DIR / 'zh_pois.gpkg', layer='all')",
        "print(f'Hex-Zellen: {len(grid)}  ·  POIs: {len(pois)}')",
        "",
        "graph_path = config.PROCESSED_DIR / 'zh_walk_graph_topo.graphml'",
        "G = ox.load_graphml(graph_path)",
        "",
        "# GraphML serialisiert alles als String — bei den Kanten-Attributen, die wir",
        "# brauchen (length, slope), zurück zu float casten.",
        "for _u, _v, data in G.edges(data=True):",
        "    if isinstance(data.get('slope'), str):",
        "        data['slope'] = float(data['slope']) if data['slope'] not in ('None', '') else None",
        "    if isinstance(data.get('length'), str):",
        "        data['length'] = float(data['length'])",
        "",
        "print(f'Graph: {len(G.nodes):,} Knoten, {len(G.edges):,} Kanten')",
    ),
    md(
        "## 3. Flat-Score (Referenz)",
        "",
        "Wir reproduzieren den flachen Score aus Notebook 05 — KDTree auf Luftlinien-Distanzen, gleiche Huff-Decay-Parameter wie im topografischen Pfad. So sind beide Scores **direkt vergleichbar**: gleiches β, gleiches Cap-Verfahren, gleiche Kategorien-Gewichte. Der einzige Unterschied ist die Distanz-Metrik.",
    ),
    code(
        "t0 = time.perf_counter()",
        "acc_flat = category_accessibility(grid, pois)",
        "score_flat = total_score(acc_flat)",
        "print(f'Flat-Score berechnet ({time.perf_counter()-t0:.1f}s)')",
        "score_flat[['hex_id', 'score']].describe()",
    ),
    md(
        "## 4. Topografischer Score (Tobler)",
        "",
        "Walking-Graph mit Tobler-Walking-Zeit gewichten, dann pro POI ein `single_source_dijkstra_path_length` mit cutoff = 15 min. Pro Zelle die Huff-gewichtete Summe der erreichbaren POIs — alles in `topographic_accessibility`.",
    ),
    code(
        "G = add_walk_time_tobler(G)",
        "",
        "t0 = time.perf_counter()",
        "acc_topo = topographic_accessibility(grid, pois, G)",
        "score_topo = total_score(acc_topo)",
        "print(f'Topografischer Score berechnet ({time.perf_counter()-t0:.1f}s)')",
        "score_topo[['hex_id', 'score']].describe()",
    ),
    md(
        "## 5. Beide Scores in einer Tabelle vereinen",
        "",
        "Ein Merge auf `hex_id` und Berechnung des Delta = topo − flat. Negative Delta = topografische Erschwernis senkt den Score. Positive Delta würde theoretisch bedeuten: Tobler ist hier schneller als 5 km/h Luftlinie (passiert bei sanfter Bergab-Kombination, aber selten bestimmend).",
    ),
    code(
        "merged = (",
        "    grid[['hex_id', 'geometry']]",
        "    .merge(score_flat[['hex_id', 'score']].rename(columns={'score': 'score_flat'}), on='hex_id')",
        "    .merge(score_topo[['hex_id', 'score']].rename(columns={'score': 'score_topo'}), on='hex_id')",
        ")",
        "merged['delta'] = merged['score_topo'] - merged['score_flat']",
        "",
        "print('=== Delta-Statistik ===')",
        "print(merged['delta'].describe().round(2))",
        "print()",
        "print(f'Zellen mit |delta| > 5:  {(merged.delta.abs() > 5).sum()} von {len(merged)}')",
        "print(f'Zellen mit  delta < -5:  {(merged.delta < -5).sum()}  (Topo schlechter als Flat)')",
        "print(f'Zellen mit  delta > +5:  {(merged.delta > +5).sum()}  (Topo besser als Flat)')",
    ),
    md(
        "## 6. Drei statische Karten nebeneinander (matplotlib)",
        "",
        "Links: flat. Mitte: topo. Rechts: delta (divergierende Skala).",
    ),
    code(
        "fig, axes = plt.subplots(1, 3, figsize=(20, 7))",
        "",
        "vmin = min(merged.score_flat.min(), merged.score_topo.min())",
        "vmax = max(merged.score_flat.max(), merged.score_topo.max())",
        "",
        "merged.plot(column='score_flat', cmap='RdYlGn', vmin=vmin, vmax=vmax,",
        "            ax=axes[0], legend=True, edgecolor='white', linewidth=0.1)",
        "axes[0].set_title(f'Flat-Score (5 km/h, Luftlinie)\\n'",
        "                  f'Median = {merged.score_flat.median():.1f}', fontsize=12)",
        "axes[0].set_axis_off()",
        "",
        "merged.plot(column='score_topo', cmap='RdYlGn', vmin=vmin, vmax=vmax,",
        "            ax=axes[1], legend=True, edgecolor='white', linewidth=0.1)",
        "axes[1].set_title(f'Topografischer Score (Tobler)\\n'",
        "                  f'Median = {merged.score_topo.median():.1f}', fontsize=12)",
        "axes[1].set_axis_off()",
        "",
        "vabs = max(abs(merged.delta.min()), abs(merged.delta.max()))",
        "merged.plot(column='delta', cmap='RdBu', vmin=-vabs, vmax=+vabs,",
        "            ax=axes[2], legend=True, edgecolor='white', linewidth=0.1)",
        "axes[2].set_title(f'Δ = Topo − Flat\\n'",
        "                  f'Range [{merged.delta.min():.1f}, {merged.delta.max():.1f}]',",
        "                  fontsize=12)",
        "axes[2].set_axis_off()",
        "",
        "fig.suptitle('15-Minuten-Stadt Zürich: flach vs. topografisch',",
        "             fontsize=14, y=1.02)",
        "fig.tight_layout()",
        "out = FIG / 'score_flat_vs_topo.png'",
        "fig.savefig(out, dpi=180, bbox_inches='tight')",
        "print('Gespeichert:', out)",
    ),
    md(
        "## 7. Top-Verlierer & Top-Gewinner",
        "",
        "Welche Quartiere sind am stärksten betroffen? Wir gruppieren auf Stadt-Zürich-Quartiere und ranken nach mittlerem Delta.",
    ),
    code(
        "quart = gpd.read_file(config.PROCESSED_DIR / 'zh_quartier_summary.gpkg', layer='quartiere')",
        "quart_lv95 = quart.to_crs(config.EPSG_LV95)",
        "merged_lv95 = merged.set_crs(grid.crs).to_crs(config.EPSG_LV95) if merged.crs is None else merged.to_crs(config.EPSG_LV95)",
        "",
        "# Centroid-basiertes Sjoin (gleicher Pattern wie NB06)",
        "merged_pts = merged_lv95[['hex_id', 'score_flat', 'score_topo', 'delta', 'geometry']].copy()",
        "merged_pts['geometry'] = merged_pts.geometry.centroid",
        "joined = gpd.sjoin(merged_pts, quart_lv95[['name', 'geometry']], how='inner', predicate='within')",
        "",
        "summary = (joined.groupby('name')",
        "           .agg(score_flat=('score_flat', 'mean'),",
        "                score_topo=('score_topo', 'mean'),",
        "                delta_mean=('delta', 'mean'),",
        "                n_zellen=('hex_id', 'count'))",
        "           .round(2)",
        "           .sort_values('delta_mean'))",
        "",
        "print('=== Top 5 Verlierer (Topo deutlich schlechter als Flat) ===')",
        "print(summary.head(5).to_string())",
        "print()",
        "print('=== Top 5 Gewinner (Topo besser oder neutral) ===')",
        "print(summary.tail(5).to_string())",
    ),
    md(
        "## 8. Interaktive Karte (Folium)",
        "",
        "Drei Layer (flat / topo / delta), umschaltbar. Wird als HTML gespeichert — kann standalone im Browser geöffnet oder in der Präsentation eingebettet werden.",
    ),
    code(
        "import folium",
        "from folium.features import GeoJsonTooltip",
        "",
        "merged_wgs = merged.set_crs(grid.crs).to_crs(config.EPSG_WGS84) if merged.crs is None else merged.to_crs(config.EPSG_WGS84)",
        "centroid = merged_wgs.geometry.union_all().centroid",
        "m = folium.Map(location=[centroid.y, centroid.x], zoom_start=12, tiles='cartodbpositron')",
        "",
        "def style_score(feature, col, vmin, vmax):",
        "    import branca.colormap as cm",
        "    cmap = cm.linear.RdYlGn_09.scale(vmin, vmax)",
        "    val = feature['properties'][col]",
        "    return {'fillColor': cmap(val), 'color': '#666', 'weight': 0.3, 'fillOpacity': 0.75}",
        "",
        "import branca.colormap as cm",
        "vabs = max(abs(merged.delta.min()), abs(merged.delta.max()))",
        "cmap_delta = cm.LinearColormap(['#b2182b', '#f7f7f7', '#2166ac'], vmin=-vabs, vmax=+vabs)",
        "",
        "fg_flat = folium.FeatureGroup(name='Score: flat (Luftlinie)')",
        "fg_topo = folium.FeatureGroup(name='Score: topografisch (Tobler)', show=True)",
        "fg_delta = folium.FeatureGroup(name='Δ = Topo − Flat', show=False)",
        "",
        "for _, row in merged_wgs.iterrows():",
        "    geom = row.geometry.__geo_interface__",
        "    folium.GeoJson(",
        "        {'type': 'Feature', 'properties': {'hex_id': row.hex_id, 'score': float(row.score_flat)}, 'geometry': geom},",
        "        style_function=lambda f: {'fillColor': cm.linear.RdYlGn_09.scale(0, 100)(f['properties']['score']),",
        "                                  'color': '#888', 'weight': 0.2, 'fillOpacity': 0.8},",
        "        tooltip=GeoJsonTooltip(fields=['hex_id', 'score'], aliases=['Hex', 'Flat-Score']),",
        "    ).add_to(fg_flat)",
        "    folium.GeoJson(",
        "        {'type': 'Feature', 'properties': {'hex_id': row.hex_id, 'score': float(row.score_topo)}, 'geometry': geom},",
        "        style_function=lambda f: {'fillColor': cm.linear.RdYlGn_09.scale(0, 100)(f['properties']['score']),",
        "                                  'color': '#888', 'weight': 0.2, 'fillOpacity': 0.8},",
        "        tooltip=GeoJsonTooltip(fields=['hex_id', 'score'], aliases=['Hex', 'Topo-Score']),",
        "    ).add_to(fg_topo)",
        "    folium.GeoJson(",
        "        {'type': 'Feature', 'properties': {'hex_id': row.hex_id, 'delta': float(row.delta)}, 'geometry': geom},",
        "        style_function=lambda f: {'fillColor': cmap_delta(f['properties']['delta']),",
        "                                  'color': '#888', 'weight': 0.2, 'fillOpacity': 0.85},",
        "        tooltip=GeoJsonTooltip(fields=['hex_id', 'delta'], aliases=['Hex', 'Δ Topo−Flat']),",
        "    ).add_to(fg_delta)",
        "",
        "fg_flat.add_to(m)",
        "fg_topo.add_to(m)",
        "fg_delta.add_to(m)",
        "cm.linear.RdYlGn_09.scale(0, 100).caption = 'Score (0–100)'",
        "cm.linear.RdYlGn_09.scale(0, 100).add_to(m)",
        "cmap_delta.caption = 'Δ (Topo − Flat)'",
        "cmap_delta.add_to(m)",
        "folium.LayerControl(collapsed=False).add_to(m)",
        "",
        "out_html = FIG / 'score_delta.html'",
        "m.save(out_html)",
        "print('Gespeichert:', out_html)",
        "m",
    ),
    md(
        "## 9. Persistierung — topografischer Score speichern",
        "",
        "Damit andere Notebooks (z. B. eine etwaige Re-Analyse oder die Präsentation) den Topo-Score nutzen können, ohne ihn neu zu berechnen.",
    ),
    code(
        "out_gpkg = config.PROCESSED_DIR / 'hex_score_topo.gpkg'",
        "merged.set_crs(grid.crs).to_file(out_gpkg, layer='hex_score_topo', driver='GPKG')",
        "print('Gespeichert:', out_gpkg)",
        "print(f'Spalten: {list(merged.columns)}')",
    ),
    md(
        "## 10. Fazit",
        "",
        "- ✅ Flat-Score und topografischer Score sind beide aus den gleichen POIs / Gewichten / β / Cutoff berechnet — direkt vergleichbar.",
        "- ✅ Drei Karten (statisch + interaktiv) zeigen die Delta-Verteilung.",
        "- ✅ Quartier-Aggregation liefert eine Verlierer-/Gewinner-Liste.",
        "- ✅ Output `hex_score_topo.gpkg` enthält flat, topo und delta in einer Tabelle.",
        "",
        "**Erwartung an die Diskussion in der Präsentation:** Hangzonen (z. B. Hottingen, Fluntern, Hirzenbach, Höngg) verlieren stärker als das flache Stadtzentrum. Das ist genau der Mehrwert der Tobler-Erweiterung gegenüber dem flachen Modell.",
    ),
]

save(OUT, nb(cells))
print("Notebook 06b geschrieben:", OUT)
