"""Erzeugt notebooks/02b_elevation.ipynb — Höhen-Anreicherung des Walk-Graphs."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_notebook import md, code, nb, save

OUT = Path(
    "/sessions/intelligent-practical-clarke/mnt/Einsatz von Geodaten in Marketing"
    "/notebooks/02b_elevation.ipynb"
)

cells = [
    md(
        "# 02b — Walking-Graph mit Höhen anreichern",
        "",
        "**Ziel:** Den Walking-Graph aus Notebook 02 um Knoten-Höhen (`z`) und Kanten-Steigungen (`slope`) anreichern. Ergebnis ist die Vorbedingung für den **topografischen Score** (Notebook 05b), der mit der Tobler-Funktion realistische Walking-Zeiten an Steigungen ableitet.",
        "",
        "**Datenquelle:** SwissALTI3D von swisstopo — siehe `docs/data_sources.md` Quelle 8 für Bezugsweg. Die GeoTIFF muss manuell heruntergeladen und nach `data/external/swissalti3d_zh.tif` gelegt werden (kein automatisierter Download wegen swisstopo-Login).",
        "",
        "**Outputs:**",
        "- `data/processed/zh_walk_graph_topo.graphml` — Walk-Graph mit `z` pro Knoten und `slope` pro Kante",
        "- Zusammenfassende Statistik der Steigungs-Verteilung",
    ),
    md("## 1. Setup"),
    code(
        "import sys",
        "from pathlib import Path",
        "ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()",
        "sys.path.insert(0, str(ROOT / 'src'))",
        "",
        "import logging",
        "logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')",
        "",
        "import osmnx as ox",
        "from zh15min import config",
        "from zh15min.elevation import (",
        "    enrich_graph_with_elevation,",
        "    compute_edge_slopes,",
        "    slope_summary,",
        "    DEFAULT_DEM_PATH,",
        ")",
        "",
        "print('DEM erwartet unter:', DEFAULT_DEM_PATH)",
    ),
    md(
        "## 2. Walking-Graph laden",
        "",
        "Wir nehmen den in Notebook 02 gespeicherten Graph (`data/processed/zh_walk_graph.graphml`). OSMnx liefert ihn als `MultiDiGraph` — wir bestätigen das, weil die Tobler-Funktion in Notebook 05b auf gerichtete Kanten angewiesen ist (bergauf vs. bergab).",
    ),
    code(
        "graph_path = config.PROCESSED_DIR / 'zh_walk_graph.graphml'",
        "if not graph_path.exists():",
        "    raise FileNotFoundError(",
        "        f'{graph_path} fehlt — bitte zuerst Notebook 02 ausführen.'",
        "    )",
        "",
        "G = ox.load_graphml(graph_path)",
        "print(f'Graph: {len(G.nodes):,} Knoten, {len(G.edges):,} Kanten')",
        "print(f'Graph-Typ: {type(G).__name__}')",
    ),
    md(
        "## 3. DEM-Verfügbarkeit prüfen",
        "",
        "Das DEM lässt sich nicht automatisch herunterladen — falls die Datei fehlt, gibt das Skript klare Anweisungen zur manuellen Beschaffung aus.",
    ),
    code(
        "if not DEFAULT_DEM_PATH.exists():",
        "    print('⚠️  SwissALTI3D fehlt. Bezugsweg:')",
        "    print('   1. https://www.swisstopo.admin.ch/de/geodata/height/alti3d.html')",
        "    print('   2. swisstopo-Login → \"swissALTI3D Daten beziehen\"')",
        "    print('   3. Ausschnitt Stadt Zürich aufziehen, GeoTIFF (LV95, 2 m)')",
        "    print(f'   4. Datei nach {DEFAULT_DEM_PATH} legen')",
        "    print()",
        "    print('Notebook 02b kann ohne DEM nicht weiter — bitte Datei beschaffen.')",
        "else:",
        "    import rasterio",
        "    with rasterio.open(DEFAULT_DEM_PATH) as ds:",
        "        print(f'DEM gefunden: {DEFAULT_DEM_PATH.name}')",
        "        print(f'  CRS: {ds.crs}')",
        "        print(f'  Shape: {ds.shape}, Auflösung: {ds.res}')",
        "        print(f'  Bounds (LV95): {tuple(round(b, 1) for b in ds.bounds)}')",
        "        print(f'  Datentyp Band 1: {ds.dtypes[0]}')",
    ),
    md(
        "## 4. Knoten-Höhen setzen",
        "",
        "OSMnx-Knoten haben Längen-/Breitengrad in WGS84. Die `enrich_graph_with_elevation`-Funktion reprojiziert on-the-fly auf das DEM-CRS (LV95) und liest Band 1 (Höhe in Metern ü. M.) pro Knoten aus. Knoten ausserhalb des DEM-Ausschnitts bekommen `z = None`.",
    ),
    code(
        "G = enrich_graph_with_elevation(G)",
        "",
        "# Stichprobe & Stats",
        "import statistics",
        "z_vals = [G.nodes[n]['z'] for n in G.nodes if G.nodes[n].get('z') is not None]",
        "print(f'Knoten mit Höhe: {len(z_vals):,} von {len(G.nodes):,}')",
        "if z_vals:",
        "    print(f'Höhen-Range: {min(z_vals):.0f} – {max(z_vals):.0f} m ü. M.')",
        "    print(f'Median: {statistics.median(z_vals):.0f} m')",
    ),
    md(
        "## 5. Kanten-Steigungen berechnen",
        "",
        "Pro gerichteter Kante wird die Steigung als `(z_v − z_u) / length` gesetzt. Da OSMnx den Graph als MultiDiGraph liefert, sind u→v und v→u getrennte Kanten — Steigung ist daher **asymmetrisch** (bergauf positiv, bergab negativ). Das ist die Voraussetzung für die Tobler-Funktion in Notebook 05b.",
    ),
    code(
        "G = compute_edge_slopes(G)",
        "",
        "summary = slope_summary(G)",
        "print('=== Steigungs-Statistik (absolut, in Prozent) ===')",
        "for k, v in summary.items():",
        "    if isinstance(v, float):",
        "        print(f'  {k:<26} {v:6.2f} %')",
        "    else:",
        "        print(f'  {k:<26} {v}')",
    ),
    md(
        "## 6. Plausibilität — Histogramm der Steigungen",
        "",
        "Erwartung für Zürich: das meiste Strassennetz mit < 5 % Steigung, ein längerer Schwanz bis ~15–20 % an den Hangzonen (Zürichberg, Hönggerberg, Käferberg, Üetliberg). Steigungen > 25 % sind selten und meist Treppen oder Wege.",
    ),
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "",
        "slopes_pct = [d['slope'] * 100 for _, _, _, d in G.edges(keys=True, data=True)",
        "              if d.get('slope') is not None]",
        "",
        "fig, axes = plt.subplots(1, 2, figsize=(12, 4))",
        "",
        "axes[0].hist(slopes_pct, bins=80, color='#065A82', edgecolor='white')",
        "axes[0].axvline(0, color='black', linewidth=0.8)",
        "axes[0].set_xlabel('Steigung [%]  (negativ = bergab)')",
        "axes[0].set_ylabel('Anzahl Kanten')",
        "axes[0].set_title('Steigungs-Verteilung (vorzeichenrichtig)')",
        "",
        "abs_slopes = np.abs(slopes_pct)",
        "axes[1].hist(abs_slopes, bins=80, color='#1C7293', edgecolor='white')",
        "for q, label in [(50, 'Median'), (75, 'P75'), (95, 'P95')]:",
        "    val = np.percentile(abs_slopes, q)",
        "    axes[1].axvline(val, color='black', linestyle='--', alpha=0.6,",
        "                    label=f'{label} = {val:.1f} %')",
        "axes[1].set_xlabel('|Steigung| [%]')",
        "axes[1].set_ylabel('Anzahl Kanten')",
        "axes[1].set_title('Absolute Steigungen')",
        "axes[1].legend()",
        "",
        "fig.tight_layout()",
        "out = config.FIGURES_DIR / 'slope_histogram.png'",
        "fig.savefig(out, dpi=180, bbox_inches='tight')",
        "print('Gespeichert:', out)",
    ),
    md(
        "## 7. Topografisch angereicherten Graph speichern",
        "",
        "OSMnx serialisiert NetworkX-Graphen nach GraphML. Die Knoten- und Kanten-Attribute (inkl. `z`, `slope`) werden mit gespeichert.",
    ),
    code(
        "out_path = config.PROCESSED_DIR / 'zh_walk_graph_topo.graphml'",
        "ox.save_graphml(G, out_path)",
        "print('Gespeichert:', out_path)",
        "",
        "# Sanity-Check: laden, prüfen, dass z + slope in der Datei sind",
        "G_check = ox.load_graphml(out_path)",
        "first_node = next(iter(G_check.nodes))",
        "first_edge = next(iter(G_check.edges(keys=True, data=True)))",
        "print('Stichprobe Knoten:', first_node, '→ z =', G_check.nodes[first_node].get('z'))",
        "print('Stichprobe Kante:', first_edge[0], '→', first_edge[1], 'slope =', first_edge[3].get('slope'))",
    ),
    md(
        "## 8. Zusammenfassung",
        "",
        "- ✅ DEM SwissALTI3D ausgewertet",
        "- ✅ Knoten-Höhen `z` gesetzt (gespeichert im Graph)",
        "- ✅ Kanten-Steigungen `slope` als asymmetrische Werte gesetzt",
        "- ✅ Topografischer Walk-Graph in `data/processed/zh_walk_graph_topo.graphml`",
        "",
        "**Nächster Schritt** (Notebook 05b): Tobler-Walking-Geschwindigkeit pro Kante ableiten und einen netzwerkbasierten Score berechnen, der die Topografie berücksichtigt.",
    ),
]

save(OUT, nb(cells))
print("Notebook 02b geschrieben:", OUT)
